#!/usr/bin/env dls-python

# Simple script for setting the TMBF into the appropriate tune measurement
# mode.
#
# This script is called from the front panel screen with the device name and one
# of the following three actions:
#
#   TUNE    Tune Only           Tune measurement, no feedback
#   AP      Tune Special        Multibunch tune only measurement
#   FB      Feedback On & Tune  Feedback and tune measurement, normal operation

from pkg_resources import require
require('cothread')
require('numpy')

import sys
import numpy
import argparse

from cothread import catools


DEFAULT_CONFIG = '/home/ops/diagnostics/config/TMBF_tune.config'

DEVICE_TO_AXIS = {
    'SR23C-DI-TMBF-01': 'X',
    'SR23C-DI-TMBF-02': 'Y',
    'TS-DI-TMBF-01': 'T',
}

VALID_SETUPS = ['TUNE', 'AP', 'FB']


def put(pv, value):
    catools.caput('%s:%s' % (DEVICE, pv), value)

def putwf(pv, value):
    put(pv, numpy.repeat(value, BUNCH_COUNT))

def get(pv, **kargs):
    return catools.caget('%s:%s' % (DEVICE, pv), **kargs)

def get_config(config, key):
    if AXIS == 'T':
        key = '%s_%s' % (AXIS, key)
    else:
        key = '%s_%s_%s' % (AXIS, key, RING_MODE)
    try:
        return config[key]
    except:
        print >>sys.stderr, 'Configuration for %s:%s in mode %s not found' % (
            AXIS, key, RING_MODE)
        raise

def compute_filter_size(tune):
    # Search for best filter size.  In this search we prefer shorter filters
    # over longer filters.
    best_error = 1
    filter = (0, 0)
    for length in range(3, N_TAPS + 1):
        for cycles in range(1, length):
            error = abs(tune - float(cycles) / length)
            if error < best_error:
                best_error = error
                filter = (cycles, length)
    return filter

def apply_overrides(config_key):
    match = config_key + '_'
    l = len(match)
    for key in globals().keys():
        if key[:l] == match:
            print 'override:', key, globals().get(key[l:]), '<=', globals()[key]
            globals()[key[l:]] = globals()[key]

def update_globals(config, setup):
    # Use settings in config file to override defaults set here.
    globals().update(config)

    # Apply setup specific overrides.
    apply_overrides(setup)

    # Apply any ring mode/axis specific overrides.
    if AXIS == 'T':
        apply_overrides(AXIS)
    else:
        apply_overrides('%s_%s' % (AXIS, RING_MODE))


# ------------------------------------------------------------------------------
# Argument parsing

parser = argparse.ArgumentParser(
    description = 'Configure device in specified setup mode.')
parser.add_argument(
    '-c', dest = 'config', default = DEFAULT_CONFIG,
    help = 'Alternative configuration file')
parser.add_argument(
    '-d', dest = 'debug', default = False, action = 'store_true',
    help = 'Enable debug mode')
parser.add_argument(
    '-m', dest = 'ring_mode', default = None,
    help = 'Specify ring mode, otherwise PV will be consulted')
parser.add_argument(
    '-t', dest = 'tune', default = None, type = float,
    help = 'Specify tune, otherwise config file will be consulted')
parser.add_argument('device', help = 'TMBF device name to configure')
parser.add_argument('setup',
    help = 'Configuration setup, must be one of TUNE, AP, FB')
args = parser.parse_args()

SETUP = args.setup

DEVICE = args.device
try:
    AXIS = DEVICE_TO_AXIS[DEVICE]
except:
    parser.error('Device \'%s\' not known' % DEVICE)
if SETUP not in VALID_SETUPS:
    parser.error('Setup mode \'%s\' is invalid' % SETUP)

if args.debug:
    def put(pv, value):
        print '%s <= %s' % (pv, value)
    def putwf(pv, value):
        print '%s <= %d*[%s]' % (pv, BUNCH_COUNT, value)

if args.ring_mode is None:
    RING_MODE = catools.caget('SR-CS-RING-01:MODE', datatype = str)
else:
    RING_MODE = args.ring_mode

# Read fundamental parameters from device
N_TAPS = get('FIR:N_TAPS')
BUNCH_COUNT = get('BUNCHES')


# ------------------------------------------------------------------------------
# Assemble final configuration to apply

CONFIG_FILE = args.config

# Load setup defaults
from setup_defaults import *

# Load the specified configuration file.  This contains overrides for the
# globals below together with settings for the mode specific default tune in a
# backwards compatible format.
CONFIG = {}
execfile(CONFIG_FILE, {}, CONFIG)

# Load tune from config file in its strange compatibility format
if args.tune is None:
    tune = 1e-4 * float(get_config(globals(), 'tune'))
else:
    tune = args.tune
cycles, length = compute_filter_size(tune)

# Apply configuration and mode specific settings
update_globals(CONFIG, SETUP)


# ------------------------------------------------------------------------------
# Write computed configuration

# First a bunch of sanity settings, in case somebody has been messing with
# stuff.
put('DAC:ENABLE_S', 'Off')        # Turn off while we mess with settings

# Make sure we're sane.
put('LOOPBACK_S', 'Normal')
put('COMPENSATE_S', 'Normal')
put('SEQ:0:BANK_S', 'Bank 0')
put('DET:RESET_WIN_S.PROC', 0)

# Ensure no triggers are running and the sequencer is stopped
put('TRG:DDR:RESET_S.PROC', 0)
put('TRG:BUF:RESET_S.PROC', 0)
put('SEQ:RESET_S.PROC', 0)

# Configure FIR as selected
put('FIR:0:LENGTH_S', length)
put('FIR:0:CYCLES_S', cycles)
put('FIR:0:USEWF_S', 'Settings')
put('FIR:GAIN_S', '-42dB')

# Configure bunch bank #0 for FIR and selected operation
putwf('BUN:0:FIRWF_S', 0)
putwf('BUN:0:OUTWF_S', dac_output)
putwf('BUN:0:GAINWF_S', 1)

# Configure sequencer
put('SEQ:1:HOLDOFF_S', 2)
put('SEQ:1:DWELL_S', sweep_dwell_time)
put('SEQ:1:GAIN_S', sweep_gain)
put('SEQ:1:ENWIN_S', 'Windowed')
put('SEQ:1:BLANK_S', 'Blanking')

# Ensure super sequencer isn't in a strange state
put('SEQ:SUPER:COUNT_S', 1)
put('SEQ:SUPER:RESET_S', 0)

# Configure detector
put('DET:MODE_S', bunch_mode)
put('DET:AUTOGAIN_S', 'Autogain')
put('DET:INPUT_S', detector_input)
put('DET:LOOP:ADC_S', 1)

# Configure tune measurement
put('TUNE:HARMONIC_S', harmonic)
put('TUNE:CENTRE_S', tune)
put('TUNE:RANGE_S', sweep_range)
put('TUNE:ALARM_S', alarm_range)
put('TUNE:BUNCH_S', bunch)
put('TUNE:DIRECTION_S', tune_direction)
put('TUNE:FEEDBACK_S', keep_feedback)
# This configures the entire tune sweep with the parameters above and sets up
# triggering correctly.
put('TUNE:SET_S.PROC', 0)

# Basic tune measurement settings
put('TUNE:BLK:LEN_S', min_block_len)
put('TUNE:BLK:SEP_S', min_block_sep)
put('TUNE:THRESHOLD_S', tune_threshold)

# Peak tune measurement settings
put('PEAK:SEL_S', peak_smoothing)
put('PEAK:THRESHOLD_S', peak_fit_threshold)
put('PEAK:FITERROR_S', peak_max_error)
put('PEAK:MINWIDTH_S', peak_min_width)
put('PEAK:MAXWIDTH_S', peak_max_width)

put('TUNE:SELECT_S', tune_select)

# Configure blanking
put('TRG:BUF:EXT:BL_S', 'All')
put('TRG:BLANKING:SOURCE_S', blanking_source)
put('TRG:BLANKING_S', blanking_interval)

put('TRG:SYNC_S', 'Separate')

# Now we can go!
put('DAC:ENABLE_S', 'On')
put('TRG:BUF:ARM_S.PROC', 0)


# vim: set filetype=python:
