#!/bin/bash

# Simple script for setting the TMBF into the appropriate tune measurement
# mode.

set -e      # Exit immediately if any command fails

HERE="$(dirname "$0")"

# Validate input parameters.
DEVICE="${1:?Specify device}"
MODE="${2:?Specify mode}"
CONFIG="${3:-/home/ops/diagnostics/concentrator/TMBF_tune.config}"


# ------------------------------------------------------------------------------
# Set up defaults before loading config file.

HARMONIC=80
BUNCH=450

tune_threshold=0.3
min_block_sep=20
min_block_len=20
sweep_dwell_time=100

sweep_range=0.05
alarm_range=0.01

# Pull in configured tune settings.  The config file contains settings for tune
# and FIR fraction cycles/length for each ring mode and axis and may optionally
# contain overrides for the defaults above.
. "$CONFIG"

# ------------------------------------------------------------------------------


Error()
{
    echo >&2 "$@"
    exit 1
}

put()
{
    [[ -n $2 ]]  ||  Error "Missing value for $1"
    caput -s $DEVICE:$1 "$2"
}


# Extract the tune settings appropriate to our device, determine the nominal
# tune and FIR shape.

case $DEVICE in
    SR21C-DI-TMBF-01)   AXIS=X ;;
    SR21C-DI-TMBF-02)   AXIS=Y ;;
    TS-DI-TMBF-01)      AXIS=X ;;
    *)                  Error Unknown device $DEVICE ;;
esac

ring_mode=$(caget -t SR-CS-RING-01:MODE | sed 's/ $//')
eval tune=\$${AXIS}_tune_$ring_mode
eval cycles=\$${AXIS}_cycles_$ring_mode
eval length=\$${AXIS}_length_$ring_mode
if [ -z "$tune" -o -z "$cycles" -o -z "$length" ]; then
    Error "Unknown ring mode $ring_mode, check PV SR-CS-RING-01:MODE"
fi
tune=0.$tune


# Settings with mode specific overrides
dac_output=0                # By default DAC output is off
bunch_mode='All Bunches'    # By default detect on all bunches
detector_input=FIR

# Mode specific settings
case $MODE in
    TUNE)   # Multibunch tune measurement
        sweep_gain=-42dB
        ;;
    SBFB)   # Feedback on, single bunch tune measurement
        sweep_gain=-24dB
        dac_output=1    # Enable FIR output in this mode
        bunch_mode='Single Bunch'
        HARMONIC=0
        ;;
    AP)
        sweep_gain=0dB
        tune=0.25
        sweep_range=0.245
        alarm_range=0.245
        detector_input=ADC
        min_block_len=5
        ;;
    *)  Error Mode must be one of TUNE, AP or SBFB.
        ;;
esac

# FIR loop delay adds an extra half FIR length
fir_loop_delay=$(echo 1 k $length 2 / p | dc)


# First a bunch of sanity settings, in case somebody has been messing with
# stuff.
put DAC:ENABLE_S Off        # Turn off while we mess with settings

# Make sure we're sane.
put LOOPBACK_S Normal
put COMPENSATE_S Normal
put SEQ:0:BANK_S 'Bank 0'
put DET:RESET_WIN_S.PROC 0

# Ensure no triggers are running and the sequencer is stopped
put TRG:S1:RESET_S.PROC 0
put TRG:S2:RESET_S.PROC 0
put TRG:EXT:RESET_S.PROC 0
put SEQ:RESET_S.PROC 0

# Configure FIR as selected
put FIR:0:LENGTH_S $length
put FIR:0:CYCLES_S $cycles
put FIR:0:USEWF_S Settings
put FIR:GAIN_S -42dB

# Configure bunch bank #0 for FIR and selected operation
echo set_one_bunch $DEVICE 0 all 0 $dac_output 1023
"$HERE"/set_one_bunch $DEVICE 0 all 0 $dac_output 1023

# Configure sequencer
put SEQ:1:HOLDOFF_S 2
put SEQ:1:DWELL_S $sweep_dwell_time
put SEQ:1:GAIN_S $sweep_gain
put SEQ:1:ENWIN_S Windowed

# Configure detector
put DET:MODE_S "$bunch_mode"
put DET:AUTOGAIN_S Autogain
put DET:INPUT_S $detector_input
put DET:LOOP:ADC_S 1
put DET:LOOP:FIR_S $fir_loop_delay

# Configure tune measurement
put TUNE:HARMONIC_S $HARMONIC
put TUNE:CENTRE_S $tune
put TUNE:RANGE_S $sweep_range
put TUNE:ALARM_S $alarm_range
put TUNE:BUNCH_S $BUNCH
put TUNE:SET_S.PROC 0

put TUNE:BLK:LEN_S $min_block_len
put TUNE:BLK:SEP_S $min_block_sep
put TUNE:THRESHOLD_S $tune_threshold

# Trigger on external trigger.
put TRG:BUF:SEL_S External
put TRG:SEQ:ENA_S Enabled
put TRG:EXT:MODE_S Retrigger

# Now we can go!
put DAC:ENABLE_S On
put TRG:EXT:ARM_S.PROC 0
