#!/bin/sh

DI_PATH="$(configure-ioc s -p DI-gui-dir)"/scripts


if (($#)); then
    device=
    case $1 in
        TS)     device=TS-DI-TMBF-01 ;;
        1|01)   device=SR23C-DI-TMBF-01 ;;
        2|02)   device=SR23C-DI-TMBF-02 ;;
        3|03)   device=SR23C-DI-TMBF-03 ;;
        *)      device="$1" ;;
    esac

    ARGS=(-m device=$device)
    FILE=tmbf/tmbf_overview.edl
else
    ARGS=()
    FILE=tmbf_launcher.edl
fi

export EPICS_CA_MAX_ARRAY_BYTES=1000000

cd "$(dirname "$(readlink -f "$0")")"

PATH="$(pwd)"/scripts:"$PATH":"$DI_PATH"
exec edm -x -eolc "${ARGS[@]}" "$FILE" &
