#!/bin/sh

. /etc/init.d/functions
. /etc/tmbf_ioc

PIDFILE=/var/run/tmbf.pid

: "${IOC_LOG:=/dev/console}"

: "${TMBF_IOC:?}"
: "${DESIGN:?}"


do_start()
{
    if [ -e "$PIDFILE" ]; then
        echo -n " - already running?"
    else
        # Load and initialise FPGA
        /opt/bin/load-fpga "$DESIGN"

        # Run as a daemon with all output sent to log file.
        "$TMBF_IOC" -n >>"$IOC_LOG" 2>&1 </dev/null &
    fi
}

do_stop()
{
    [ -e "$PIDFILE" ]  &&  kill "$(cat "$PIDFILE")"
    rm -f "$PIDFILE"
}

do_restart()
{
    "$0" stop
    sleep 1
    "$0" start
}

do_start_stop "$1" TMBF
