#!/bin/sh

. /etc/init.d/functions
. /etc/tmbf_ioc

: "${IOC_LOG:=/dev/console}"

: "${TMBF_IOC:?}"
: "${DESIGN:?}"


do_start()
{
    if [ -e /var/run/ioc.pid ]; then
        echo -n " - already running?"
    else
        # Load and initialise FPGA
        /opt/bin/load-fpga "$DESIGN"

        # Ensure MSP driver is running
#         modprobe msp

        # Run as a daemon with all output sent to log file.
        "$TMBF_IOC" -n >>"$IOC_LOG" 2>&1 </dev/null &
    fi
}

do_stop()
{
    [ -e /var/run/ioc.pid ]  &&  kill "$(cat /var/run/ioc.pid)"
    rm -f /var/run/ioc.pid

#     modprobe -r msp
}

do_restart()
{
    "$0" stop
    sleep 1
    "$0" start
}

do_start_stop "$1" TMBF
