#!/bin/sh

INSTALL_DIRS='runioc bin dbd db base scripts install_d'


SOURCE="$(cd "$(dirname "$0")"/..; pwd)"
. "$SOURCE"/install_d/CONFIG
if (($# > 0)); then
    INSTALL_HOST="$1"
else
    : ${INSTALL_HOST:?Local installation path not defined}
fi

# Erase everything in the target directory: start from scratch on each
# install.
TARGET="$INSTALL_HOST"/tmbf
rm -rf "$TARGET"
mkdir -p "$TARGET"/install_d

# Copy over the appropriate components
for dir in $INSTALL_DIRS; do
    cp -r "$SOURCE/$dir" "$TARGET"
done

echo TMBF IOC installed in "$TARGET".
