#!/bin/sh

INSTALL_FILES='
    CONFIG
    epics
    runioc
    st.cmd
    pbpm-install-ioc'

INSTALL_DIRS='bin dbd db'


SOURCE="$(cd "$(dirname "$0")"/..; pwd)"  
. "$SOURCE"/install/CONFIG  
if (($# > 0)); then
    INSTALL_HOST="$1"
    FPGA_SOURCE="$2"
else
    : ${INSTALL_HOST:?Local installation path not defined}
fi

# Erase everything in the target directory: start from scratch on each
# install.
TARGET="$INSTALL_HOST"/pbpm
rm -rf "$TARGET"
mkdir -p "$TARGET"/install

# Copy over the appropriate components
for dir in $INSTALL_DIRS; do
    cp -r "$SOURCE/$dir" "$TARGET"
done

# Copy over the installation specific files into the install directory.
for f in $INSTALL_FILES; do
    cp "$SOURCE"/install/$f "$TARGET"/install
done

# To be friendly create a redirector script to invoke the true runioc script.
# This is only intended for testing use.
cat <<'EOF' >"$TARGET/runioc"
#!/bin/sh
"$(dirname "$0")/install/runioc" "$@"
EOF
chmod +x "$TARGET/runioc"

echo PBPM IOC installed in "$TARGET".
