#!/bin/sh


cd "$(dirname "$0")/.."


# Defaults
PIDFILE=/var/run/ioc.pid
BIN_DIR=./bin/linux-ppc405
DAEMON=

# Argument parsing
while getopts 'nh' option; do
    case "$option" in
    n)  DAEMON=-n ;;
    h)  cat <<'EOF'
Usage: runioc [options]
    -n          run non-interactive without an IOC shell
EOF
        exit 0 ;;
    *)  echo >&2 'Invalid arguments: try -h for help'
        exit 1 ;;
    esac
done
# No extra arguments allowed
if [ $# -ge $OPTIND ]; then
    echo >&2 'Invalid arguments: try -h for help'
    exit 1
fi


# Environment needed by IOC
export EPICS_CA_MAX_ARRAY_BYTES=1000000
export HOSTNAME="$(hostname)"


# Now run the IOC.
echo
echo 'Starting IOC at' $(date)
echo "IOC parameters: $DAEMON -p '$PIDFILE'"
trap 'rm -f "$PIDFILE"' EXIT
"$BIN_DIR"/pbpm $DAEMON -p "$PIDFILE" install/st.cmd
echo 'IOC stopped at' $(date)
echo
