#!/bin/sh

cd "$(dirname "$(readlink -fn "$0")")"

which edm >/dev/null 2>&1  ||
    PATH=/dls_sw/epics/R3.14.8.2/extensions/bin/linux-x86/:"$PATH"
PATH="$(pwd)"/scripts:"$PATH"

export EPICS_CA_MAX_ARRAY_BYTES=1000000
edm -x -eolc launcher.edl &
